### ISSUE TITLE
[Insight] A Symfony2 application should be bootable

### ISSUE THREAD

**Issue by pborreli** [pborreli/composer-service#125]
> SensioLabsInsight was not able to boot your Symfony2 application. If you need to customize files or run commands to make it bootable, you can edit your SensioLabsInsight project configuration to override the default "pre_composer_script" and/or "post_composer_script" settings.

```
An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused in /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
Stack trace:
#0 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(133): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException(&#039;An exception oc...&#039;, Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException))
#2 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, &#039;root&#039;, NULL, Array)
#3 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#5 /home/foobar/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#6 /home/foobar/code/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(81): Doctrine\DBAL\Connection->getDatabasePlatform()
#7 /home/foobar/code/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(108): Doctrine\ORM\Mapping\ClassMetadataFactory->initialize()
#8 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php(69): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata()
#9 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php(48): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp(&#039;/home/foobar/co...&#039;)
#10 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(546): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp(&#039;/home/foobar/co...&#039;)
#11 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#12 /home/foobar/code/app/InsightAppKernel.php(15) : eval()&#039;d code(7): Symfony\Component\HttpKernel\Kernel->boot()
#13 /home/foobar/code/app/InsightAppKernel.php(15): eval()
#14 {main}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/20408423-f871-4d67-a87c-8967bedd6ef7/analyses/218)_

**Comment by cordoval** [comment]
how did you solve this?

**Comment by pborreli** [comment]
see 1b7cf1b when you specify the version number of MySQL, console doesn't need to connect on boot

**Comment by cordoval** [comment]
yep i did the same but for postgres thanks 👍 👴
